name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          dosfstools mtools gparted gcc m4 help2man make \
          cmake git bison libopts25 libselinux1-dev python3 \
          libopts25-dev flex automake autotools-dev autopoint \
          libfreetype6-dev texinfo autogen autoconf libtool \
          libfuse3-3 unifont gettext pkg-config liblzma5 \
          libdevmapper-dev binutils xorriso nasm

    - name: Build GRUB
      run: |
        
        # set -e
        # wget https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz
        # tar -xf grub-2.12.tar.xz
        # cd grub-2.12
        
        # Build EFI64
        # mkdir EFI64 && cd EFI64
        # ../configure --target=x86_64 --with-platform=efi
        # make -j$(nproc)
        # cd ..
        
        # Build EFI32
        # mkdir EFI32 && cd EFI32
        # ../configure --target=i386 --with-platform=efi
        # make -j$(nproc)
        # cd ..
        
        # Build BIOS
        # mkdir BIOS && cd BIOS
        # ../configure --target=i386 --with-platform=pc --disable-nls
        # make -j$(nproc)
        echo Passed...

    - name: Repack ISO
      run: |
        cmake -G Ninja
        ./scripts/repack_iso.sh

    - uses: actions/upload-artifact@v4
      with:
        name: iso
        path: targets/x86_64/iso
